default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    Dir.chdir "../.." do sh("flutter", "build", "ios", "--release", "--no-codesign") end
    increment_version_number(
        xcodeproj: "Runner.xcodeproj",
        version_number: flutter_version()["version_name"]
    )
    increment_build_number(
        xcodeproj: "Runner.xcodeproj",
        build_number: flutter_version()["version_code"]
    )
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight(
        api_key_path: "fastlane/authorization.json"
    )
  end
end
