default_platform(:ios)

platform :ios do
 desc "Push a new beta build to TestFlight"
  lane :beta do
    Dir.chdir "../.." do sh("flutter", "build", "ios", "--release", "--no-codesign") end
    api_key = app_store_connect_api_key(
        key_id: ENV['key_id'],
        issuer_id: ENV['issuer_id'],
        key_content: ENV['key'],
        duration: 1200,
        in_house: false
    )

    increment_version_number(
        xcodeproj: "Runner.xcodeproj",
        version_number: flutter_version()["version_name"]
    )
    increment_build_number(
        xcodeproj: "Runner.xcodeproj",
        build_number: flutter_version()["version_code"]
    )
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight(
        api_key: api_key
    )
  end
end
