default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean")
    Dir.chdir "../.." do sh("flutter", "build", "appbundle", "--release") end
    gradle(
        task: "bundle",
        build_type: "Release",
        print_command: true,
        properties: {
            "android.injected.signing.store.file" => ENV['PWD'] + ENV['ANDROID_APP_SIGNING_KEY'],
            "android.injected.signing.store.password" => ENV['ANDROID_APP_SIGNING_STORE_PASSWORD'],
            "android.injected.signing.key.alias" => ENV['ANDROID_APP_SIGNING_KEY_ALIAS'],
            "android.injected.signing.key.password" => ENV['ANDROID_APP_SIGNING_KEY_PASSWORD'],
        }
    )
    upload_to_play_store(
        track: 'internal',
        json_key_data: ENV['key'],
        version_code: flutter_version()["version_code"],
        version_name: flutter_version()["version_name"],
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        skip_upload_screenshots: true,
        skip_upload_images: true
    )
  end
end
