default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    Dir.chdir "../.." do sh("flutter", "build", "appbundle", "--release") end
    gradle(task: "clean assembleRelease")
    upload_to_play_store(
        track: 'internal',
        json_key_data: ENV['key'],
        version_code: flutter_version()["version_code"],
        version_name: flutter_version()["version_name"],
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        skip_upload_screenshots: true,
        skip_upload_images: true
    )
  end
end
